name: ez_barcode
description: Barcode to scan and show a group of barcodes

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  barcode_widget: ^2.0.3
  flutter_barcode_scanner: ^2.0.0
  sqflite: ^2.1.0+1
  path: ^1.8.2
  shared_preferences: ^2.0.15
  date_format: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700

flutter_icons:
  android: 'launcher_icon'
  ios: false
  image_path: 'assets/icon/icon.png'
  min_sdk_android: 21
  web:
    generate: false
    image_path: 'assets/icon/icon.png'
    background_color: '#2c6bd1'
    theme_color: '#2c6bd1'
  windows:
    generate: false
    image_path: 'assets/icon/icon.png'
    icon_size: 48 # min:48, max:256, default: 48

